Revised description and API
WebAssembly/js-promise-integration pull request #8
Opened 2022-07-22 23:05 UTC by fgmccabe

Uses a modification of WebAssembly.Function constructor

Equivalent to a static-only version of previous API

2022-08-09 17:43 UTC, RossTate requested changes

2022-08-09 17:43 UTC, RossTate commented on proposals/js-promise-integration/Overview.md
> +A responsive application is able to respond to new requests even while suspended for existing ones. Note that we are not concerned with _multi-threaded_ applications (which can also be responsive): o
```suggestion
A responsive application is able to respond to new requests even while suspended for existing ones. Note that we are not concerned with _multi-threaded_ applications (which can also be responsive): only one computation is expected to be active at any one time and all others would be _suspended_. Typically, such responsive applications are already crafted using an eventloop style architecture; even if they still use synchronous APIs.
```

2022-08-09 17:43 UTC, RossTate commented on proposals/js-promise-integration/Overview.md
> +     (locals $suspender_copy externref)
```suggestion
     (local $suspender_copy externref)
```
... I believe

2022-08-09 17:43 UTC, RossTate commented on proposals/js-promise-integration/Overview.md
> +```
```suggestion
The constructor for `WebAssembly.Function`, when it has a `suspending` attribute in its `usage` dictionary:
```
The function argument might not be typed.

2022-08-09 17:43 UTC, RossTate commented on proposals/js-promise-integration/Overview.md
> +  { parameters: ["externref", "t0", .., "tn"], results: [r0, .., rk]}
```suggestion
  { parameters: ["externref", t0, .., tn], results: [r0, .., rk]}
```

2022-08-09 17:43 UTC, RossTate commented on proposals/js-promise-integration/Overview.md
> +  { parameters: ["t0", .., "tn", "externref"], results: [r0, .., rk]}
```suggestion
  { parameters: [t0, .., tn, "externref"], results: [r0, .., rk]}
```

2022-08-09 17:43 UTC, RossTate commented on proposals/js-promise-integration/Overview.md
> +  { parameters: ["t0", .., "tn"], results: [r0, .., rk]}
```suggestion
  { parameters: [t0, .., tn], results: [r0, .., rk]}
```

2022-08-09 17:43 UTC, RossTate commented on proposals/js-promise-integration/Overview.md
> +The WebAssembly function returned by `WebAssembly.Function`, when used as an import during module instantiation, is a function whose behavior is determined as follows:
```suggestion
The WebAssembly function returned by `WebAssembly.Function` is a function whose behavior is determined as follows:
```

2022-08-09 17:43 UTC, RossTate commented on proposals/js-promise-integration/Overview.md
> +if the value of `promising` is `"first"`, and `func` should be of type:
```suggestion
or of type:
```

2022-08-15 21:22 UTC, fgmccabe commented
Have substantially reflected reviewer's requests

2022-08-15 21:23 UTC, merged